//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRegSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Registers = new HashSet<Register>();
        }
    
        [Required(ErrorMessage = "Email is Required")]
        [StringLength(35, ErrorMessage = "Email has to be less than 35 characters")]
        [RegularExpression(@"^[a-zA-Z0-9]+@[a-zA-Z0-9]+(\.[a-zA-Z]+)*$", ErrorMessage = "Email is not Valid")]
        [Remote("IsAlreadySignedUpClient", "Client", ErrorMessage = "Email already exists in database.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Fullname is Required")]
        [StringLength(25, ErrorMessage = "Fullname has to be less than 25 characters")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Address is Required")]
        [StringLength(50,ErrorMessage = "Address has to be less than 50 characters")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Age is Required")]
        public int Age { get; set; }

        [Required(ErrorMessage = "Phone Number is Required")]
        [StringLength(15, ErrorMessage = "Phone Number has to be less than 15 characters")]
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Register> Registers { get; set; }
    }
}
