//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRegSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Registers = new HashSet<Register>();
        }

        [Required(ErrorMessage = "Event Name is Required")]
        [StringLength(25, ErrorMessage = "Event Name has to be less than 25 characters")]
        public string EventName { get; set; }

        [StringLength(60, ErrorMessage = "Event Description has to be less than 60 characters")]
        public string Description { get; set; }

        [StringLength(20, ErrorMessage = "Event Location has to be less than 20 characters")]
        public string Location { get; set; }

        [Required(ErrorMessage = "Date is Required")]
        [RegularExpression("[0-9]{2}[-|/]{1}[0-9]{2}[-|/]{1}[0-9]{4}", ErrorMessage = "Date is not Valid")]
        [StringLength(10, ErrorMessage = "Event Date has to be less than 10 characters")]
        public string Date { get; set; }

        [Required(ErrorMessage = "Ticket Fee is Required")]
        public decimal TicketFee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Register> Registers { get; set; }
    }
}
