//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRegSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Register
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Guest Number is Required")]
        public int GuestNumber { get; set; }

        [Required(ErrorMessage = "Payment Amount is Required")]
        public decimal PaymentAmount { get; set; }

        [Required(ErrorMessage = "Event must be chosen")]
        [StringLength(25, ErrorMessage = "Event Name has to be less than 25 characters")]
        public string EventName { get; set; }

        [Required(ErrorMessage = "Email is Required")]
        [StringLength(35, ErrorMessage = "Email has to be less than 35 characters")]
        public string Email { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Event Event { get; set; }
    }
}
